markdown: kramdown
permalink: /:year/:month/:day/:title/
url: http://guoshixian.com
author: Lao Guo
#pygments: true
#safe: true
paginate: 25
paginate_path: "/page/:num/"
gems: [jekyll-paginate]

#auto: true
encoding: "utf-8"
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
#  syntax_highlighter_opts:: {disable: true}

# Time Zone +8 China
timezone: Asia/Shanghai

###User define variants
#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: 

#baidu tongji
baiduTongji:
  config: false
  id: 

#comment config
disqus:
  config: true
  id: guoshixian

duoshuo:
  config: false
  id: 

#baidu share config
baiduShare:
  config: false

